# Generated by Django 4.2.5 on 2023-09-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Booked_on',
            new_name='booked_on',
        ),
    ]
