# Generated by Django 4.2.5 on 2023-09-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_booked_on_booking_booked_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc_about',
            field=models.CharField(blank='true', max_length=500, null='true'),
            preserve_default='true',
        ),
    ]
