# Generated by Django 4.2.5 on 2023-09-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_doctors_doc_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc_phone',
            field=models.IntegerField(blank='true', max_length=10, null='true'),
            preserve_default='true',
        ),
    ]
