# Generated by Django 4.2.5 on 2023-09-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_doctors_doc_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_phone', models.IntegerField(max_length=10)),
                ('c_address', models.CharField(blank='true', max_length=300, null='true')),
                ('c_sub', models.CharField(max_length=500)),
            ],
        ),
    ]
