# Generated by Django 4.2.5 on 2024-02-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='c_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_phone',
            field=models.IntegerField(blank='true', null='true'),
        ),
    ]
